#ifndef QTIVIVEHICLEFUNCTIONSGLOBAL_H
#define QTIVIVEHICLEFUNCTIONSGLOBAL_H

#include <QtCore/qglobal.h>

QT_BEGIN_NAMESPACE

#ifndef QT_STATIC
#  if defined(QT_BUILD_QTIVIVEHICLEFUNCTIONS_LIB)
#    define Q_QTIVIVEHICLEFUNCTIONS_EXPORT Q_DECL_EXPORT
#  else
#    define Q_QTIVIVEHICLEFUNCTIONS_EXPORT Q_DECL_IMPORT
#  endif
#else
#  define Q_QTIVICORE_EXPORT
#endif

QT_END_NAMESPACE

#endif // QTIVIVEHICLEFUNCTIONSGLOBAL_H

